package com.toj.demo.entity;

import java.io.Serializable;
import lombok.Data;

/**
 * @TableName order
 */
@Data
public class Order implements Serializable {
    /**
     * 
     *
     * @mbg.generated Sat Jan 23 20:30:29 JST 2021
     */
    private Integer orderNo;

    /**
     * 
     *
     * @mbg.generated Sat Jan 23 20:30:29 JST 2021
     */
    private String orderDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order
     *
     * @mbg.generated Sat Jan 23 20:30:29 JST 2021
     */
    private static final long serialVersionUID = 1L;
}