package com.toj.demo.entity;

import lombok.Data;

import java.io.Serializable;

/**
 * @TableName toj_order
 */
@Data
public class TojOrder implements Serializable {
    /**
     * 
     *
     * @mbg.generated Sat Jan 30 21:32:59 JST 2021
     */
    private Integer orderNo;

    /**
     * 
     *
     * @mbg.generated Sat Jan 30 21:32:59 JST 2021
     */
    private String orderDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table toj_order
     *
     * @mbg.generated Sat Jan 30 21:32:59 JST 2021
     */
    private static final long serialVersionUID = 1L;
}